name: setup
author: Sean Darley
description: setup workflow properties
inputs:
  env:
    description: envivronment to deploy to
    required: true
    default: ''
  branch:
    description: git branch
    required: false
  deploy-suffix:
    description: deploy-suffix to clean
    default: ''
outputs:
  node-env:
    description: webpack build environment
  brand-deploy-suffix:
    description: url friendly suffix to include with brand
runs:
  using: node16
  main: dist/index.js
