name: Get jira issues in release
author: Sean Darley
description: Get Jira issues in release
inputs:
  pr-number:
    description: pr number
    required: true
    default: ''
  token:
    description: github token
    required: true
outputs:
  jira-issues:
    description: csv of jira issues in release
runs:
  using: node20
  main: 'dist/index.js'
