name: re-usable test across repos

on:
  workflow_call:
    inputs:
      NAME:
        description: 'Name from the caller workflow'
        default: 'bob'
        required: true
        type: string

jobs:
  print-caller-value:
    runs-on: unbuntu-latest
    steps:
      - name: echo name from caller workflow
        run: echo "the name from the caller workflow"