name: "Conditional envs"

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        brand: [ argos, habitat ]

    uses: ./.github/workflows/re-usable-matrix-output-workflow.yml
    with:
      brand: ${{ matrix.brand }}

  pick:
    name: Docker image names
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      run: |
        echo "dockerTag=argos" >> $GITHUB_ENV
      if: contains(matrix.brand , 'argos')
        echo "docker tags is ${{ env.dockerTag }}"

