name: "Conditional envs"

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        brand: [ argos, habitat ]

    uses: ./.github/workflows/re-usable-matrix-output-workflow.yml

  pick:
    name: Docker image names
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - run: echo ${{ needs.test.outputs.argosTag }} ${{ needs.test.outputs.habitatTag }}

