name: "Conditional envs"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      argosTag: ${{ steps.step1.outputs.argosTag }}
      habitatTag: ${{ steps.step2.outputs.habitatTag }}
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - name: Sets habitat docker env var
        run: |
          echo "habitatTag=blar blar blar${{ matrix.brand }}" >> $GITHUB_OUTPUT
        if: startsWith(matrix.brand, 'habitat')

      - name: Sets argos docker env var
        run: |
          echo "argosTag=blar blar blar${{ matrix.brand }}" >> $GITHUB_OUTPUT
        if: startsWith(matrix.brand, 'argos')

  pick:
    name: Docker image names
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - name: Set output
        run: |
          echo "this should be argos tag ${{ needs.test.outputs.argosTag }}"

