name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release name (NAP-GLOBAL-FY24-7.3)'
        required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.releaseName }}
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.releaseName }}
      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.releaseName }}
          base: main
          title: "Release: ${{ github.event.inputs.releaseName }}"
          body: |
            :exclamation: Before merging please check release workflow and ensure acceptance tests are :green_apple: :exclamation:
            [Release worflow ](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yml)
