name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      hotfix:
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
#      - name: branch prefix
#        id: branch
#        run: echo "prefix=${{ !inputs.hotfix && 'release' || 'hotfix' }}" >> $GITHUB_OUTPUT
      - name: Get current time
        id: release
        run: echo "name=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
      - name: Create branch name
        id: branch
        run:
          echo "name=${{ !inputs.hotfix && format( 'release/{0}', steps.release.outputs.name || github.ref_name) }}" >> $GITHUB_OUTPUT
      - name: display branch name
        run: echo "branch name is ${{ steps.branch.outputs.name }}"
#      - name: Show current time
#        run: echo "Current time is ${{ steps.release.outputs.name }}"
#      - name: Create release branch
#        run: git checkout -b release/${{ steps.release.outputs.name }}
#      - name: Push new branch
#        run: git push origin release/${{ steps.release.outputs.name }}
#      - name: Create pull request into main
#        uses: thomaseizinger/create-pull-request@1.3.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          head: release/${{ steps.release.outputs.name }}
#          base: main
#          title: "Release: ${{ steps.release.outputs.name }}"
#          body: |
#            :exclamation: Before merging please check release workflow and ensure acceptance tests are :green_apple: :exclamation:
#            [Release worflow ](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yml)
