on:
  push:
    branches:
      - main


tag_release:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get release commit
      id: release-commit
      run: echo "hash=$(git rev-list HEAD | head -2 | tail -1)" >> $GITHUB_OUTPUT
    - name: Create release tag
      run: |
        git checkout $(steps.release-commit.outputs.hash)
        git tag -a "v1.0" -m "Release v1.0"
        git push origin "v1.0"