on:
  push:
    branches:
      - main

jobs:
  release-sha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.releaseCommit.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Get release commit
        id: releaseCommit
        run: |
          echo "sha=$(git rev-list HEAD | head -2 | tail -1)" >> $GITHUB_OUTPUT

  create-tag:
    needs: [ release-sha ]
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.createTag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: create-tag
        id: createTag
        run: |
          git tag v1.99 ${{ needs.release-sha.outputs.sha }}
          git push origin v1.99
          echo "id=v1.99" >> $GITHUB_OUTPUT
#      - name: Checkout release commit
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ steps.releaseCommit.outputs.sha }}

  create-release:
    needs: [ create-tag ]
    #    needs: [ create-change-log ]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create-tag.outputs.release-tag }}
          generateReleaseNotes: true
#      - name: release sha
#        run: echo "the release commit ${{ github.event.pull_request.head.sha }}"



#      - name: Github commit sha of release commit
#        run: echo "github commit sha of release commit $(git rev-parse HEAD)"


          

#  update-release:
#    needs: [ release-sha ]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ needs.release-sha.outputs.sha }}
#
#      - name: github release sha
#        run: |
#          echo "release sha ${{ needs.release-sha.outputs.sha }}"
#      - name: Github commit sha
#        run: echo "github commit sha on checkout of ref $GITHUB_SHA"
#      - name: Get merged branch name
#        id: get_merged_branch
#        run: |
#          branch_name=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | \
#            jq -r '.[0].head.ref')
#
#          echo "BRANCH_NAME=${branch_name#*/}" >> $GITHUB_ENV
#
#      - name: Display merged branch name
#        run: |
#          echo "Merged branch: ${{ env.BRANCH_NAME }}"

#      - uses: rickstaa/action-create-tag@v1
#        id: "tag_create"
#        with:
#          commit_sha: ${{ steps.releaseCommit.outputs.sha }}
#          tag: ${{ env.BRANCH_NAME }}
#          tag_exists_error: false
#          message: "Release: ${{ env.BRANCH_NAME }}"

#      - uses: ncipollo/release-action@v1
#        with:
#          name: "Release: ${{ env.BRANCH_NAME }}"
#          tag: ${{ env.BRANCH_NAME }}
#          commit: ${{ steps.releaseCommit.outputs.sha }}


#      - name: Get release Id
#        id: release
#        run: |
#          git fetch origin refs/notes/commits:refs/notes/commits
#          notes_output="$(git notes show ${{ needs.release-sha.outputs.sha }})"
#          echo "id=${notes_output#*:}" >> $GITHUB_OUTPUT
#
#      - name: git notes output
#        run: |
#          echo "output from step ${{ steps.release.outputs.id }}"
#
#      - name: Update Release
#        uses: irongut/EditRelease@v1.2.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          id: ${{ steps.release.outputs.id }}
#          prerelease: false

#      - name: update release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: 'fcds999'
#          draft: true
#          prerelease: true

#      - name: Update pre-release
#        uses: actions/github-script@v4
#        with:
#          script: |
#            await github.repos.updateRelease({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              release_id: ${{ steps.release.outputs.id }},
#              prerelease: false
#              draft: false
#            });

#
#
#
#
#        run: |
#          releaseId="${{ steps.release.outputs.id }}"
#          id=${releaseId#*:}
#          echo "we have the release id $id"
