on:
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3
      - run: echo "$GITHUB_CONTEXT"
      - run: git notes add -m 'realeaseId:454544555' -f
#      - name: Create release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: 'friday-evening'
#          release_name: Release 'friday evening'
#          draft: false
#          prerelease: false
