on:
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'friday-evening'
          release_name: Release 'friday evening'
          draft: false
          prerelease: false
