name: "Deploy suffix example"

on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    name: 'Geneate the deploy suffix for sub-environment'
    steps:
      - uses: actions/checkout@v2
      - name: list directory
        run: |
          ls -a
      - uses: ./.github/actions/deploy-suffix
        name: get deploy-suffix from action
        id: deploy-suffix
        with:
          brand: argos
          deploy-suffix: 'features/NAV-1898-blar-blar'
      - name: output deploy-suffix
        run: echo ${{  steps.deploy-suffix.outputs.value }}

