on:
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'pre-release'
          release_name: Release 'FY25-343433'
          draft: true
          prerelease: true
