name: "Get jira issues in release"
run-name: Get jira issues in release
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    name: 'Get jira issues in release'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/getIssuesInRelease
        name: get jira issue from release pr
        id: jira
        with:
          pr-number: 1719
          repo-name: argos-pdp-ui-service
          issue-regex: '(NAP-\\d+)'
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
      - name: output jira issues in release
        run: echo "here we are ${{ steps.jira.outputs.jira-issues }}"
