name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      run-acceptance-tests:
        description: 'Run the Acceptance Tests?'
        required: true
        default: false
      brand:
        type: choice
        required: true
        default: all
        description: 'BRAND - Choose brand environment.'
        options:
          - all
          - argos
          - habitat
          - tu
      url-ext:
        description: 'Enter a custom name for this app all lowercase'
        required: true
      stub-service-endpoint:
        description: 'Override stub service endpoint'
        required: false
      deploy-to:
        description: 'Deploy to dev/staging/'
        require: true
        default: dev
        options:
          - dev
          - staging

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: configureEnvironmentVariables
        run: echo "maybe an action to do this"

  create-and-publish-docker-image:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "call /reusable-build.yaml here"

  acceptance-tests:
    needs:
      - setup
      - create-and-publish-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: run acceptance tests
        run: echo "call /.github/workflows/reusable-wdio-acceptance.yaml"
