name: Manual Deploy Workflow
run-name: ${{ github.actor }} is manually deploying
on:
  workflow_dispatch:
    inputs:
      brand:
        type: choice
        options:
          - argos
          - habitat
          - tu
      env:
        type: choice
        options:
          - dev
          - stg
      deploy-suffix:
        type: string
        description:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-env: ${{ steps.conf-env.outputs.node-env }}
      brand-deploy-suffix: ${{ steps.conf-env.outputs.brand-deploy-suffix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure environment variables
        id: conf-env
        uses: ./.github/actions/setup
        with:
          env: ${{ inputs.env }}
          branch: ${{ github.ref_name }}
          deploy-suffix: ${{ inputs.deploy-suffix }}
      - name: get head commit
        id: release-docker-tag
        run: |
          echo "release-docker-tag=$(git rev-list HEAD | head -2 | tail -1 |  cut -c 1-8)" >> $GITHUB_OUTPUT
      - name: output docker tag
        run: echo "docker tag ${{ steps.release-docker-tag.outputs.release-docker-tag }}"

  test-output:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: test output
        run: echo "do we have the value ${{ inputs.brand }}${{ needs.setup.outputs.brand-deploy-suffix }}"

  upload-s3-assets:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: upload s3 assets
        run: echo "todo"
