name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      run-acceptance-tests:
        description: 'Run the Acceptance Tests?'
        required: true
        default: true
      brand:
        type: choice
        required: true
        description: '\nBRAND - Choose brand environment.\n\n- all: Trigger a new build to deploy to Habitat whilst continuing with Argos deployment.\n- argos: application name - ui-global-service\n- habitat: application name - ui-global-service-habitat \n\n'
        options:
          - argos
          - habitat
          - tu
      url-ext:
        description: '✏️  URL_EXT - Enter a custom name for this app all lowercase \n\n Example:\n - branch-bug-fix -  ui-global-service-branch-bug-fix.service.eu-west-1.dev.deveng.systems\n\n'
        required: true
        default: ${{ env.GITHUB_REF }}

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
