name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      run-acceptance-tests:
        description: 'Run the Acceptance Tests?'
        required: true
        default: true
      brand:
        type: choice
        required: true
        description: 'BRAND - Choose brand environment.'
        options:
          - argos
          - habitat
          - tu
      url-ext:
        description: '✏️  URL_EXT - Enter a custom name for this app all lowercase'
        required: true
      stub-service-endpoint:
        description: 'Override stub service endpoint
        required: false
      deploy-to:
        description: 'Deploy to dev/staging
        require: true
        default: dev
        options:
          - dev
          - staging

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
