on:
  push:

jobs:
  job1:
    strategy:
      matrix:
        env: [ dev ]
        brand: [ argos, habitat ]

    runs-on: ubuntu-latest
    if: ${{ matrix.brand === argos }}
      outputs:
        output1: ${{ steps.step1.outputs.test }}
#      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}