on:
  push:

jobs:
  test:
    strategy:
      runs-on: ubuntu-latest
      matrix:
        brand: [ argos, habitat ]

    steps:
      - id: one
        run: |
          mkdir -p images
          echo ${{ matrix.brand }} >> outputs/${{ matrix.brand }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/${{ matrix.brand }}.txt


  getval:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Load outputs
        uses: actions/download-artifact@v3
        with:
          name: outputs
          path: outputs

      - run: |
          ls outputs
          cat outputs/*.txt