name: "CI/CD"

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p image
      - run: echo "hello image name for ${{matrix.brand}}" > ${{ matrix.brand }}.txt
      - uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: ${{ matrix.brand }}.txt

  pick:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: docker-images
      - shell: bash
        run: |
          value=`cat ${{ matrix.brand }}.txt`
          echo "${{ matrix.brand }}-image=$(echo $value)" >> $GITHUB_ENV
          env
