name: "CI/CD"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - uses: actions/checkout@v3
      - run: echo "hello image name for ${{matrix.brand}}" > ${{ matrix.brand }}.txt
      - uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: ${{ matrix.brand }}.txt

  pick:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
#      - name: Download artifacts
#      - id: set_var
      - uses: actions/download-artifact@v3
      - run: echo "hello ${{matrix.brand}}"
        with:
          name: docker-images

#      - name: Display structure of downloaded files
#        run: ls -R
#        run: |
#          value=`cat ${{ matrix.brand }}.txt`
#          echo "do we have a value: $value"
#          echo "::set-output name=imageName::$content"
##          echo "sorted ${{steps.set_var.outputs.imageName}}"
