name: "CI/CD"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - name: Write docker tag to file
      - uses: actions/checkout@v3
      - run: echo "hello image name for ${{matrix.brand}}" > ${{ matrix.brand }}.txt
      - uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: ${{ matrix.brand }}.txt

  pick:
    name: Docker image
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [ argos, habitat ]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Set output
        id: set_var
        run: |
          value=`cat ${{ matrix.brand }}.txt`
          echo "do we have a value: $value"
          echo "imageName=$value" >> $GITHUB_ENV

      - name: echo env var
        run: |
          echo "we have it at last : ${{ env.imageName}}"
