name: "CI/CD"

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kv:
          - key: one
            val: ONE
          - key: two
            val: TWO
          - key: three
            val: THREE

    steps:
      - id: one
        run: |
          echo ${{ matrix.kv.val }} >> outputs/${{ matrix.kv.key }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: outputs/*.txt


  getval:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Load outputs
        uses: actions/download-artifact@v3
        with:
          name: outputs
          path: outputs

      - run: |
          ls outputs
          cat outputs/*.txt