on:
  push:
    branches:
      - main

jobs:
  get-pr-number:
    if: contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Number
        id: get_pr_number
        run: |
          echo "github ref is $GITHUB_REF"
          PR_NUMBER=$(echo $GITHUB_REF | grep -oP '(?<=refs/pull/)\d+')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Print PR Number
        run: echo "The PR number is ${{ env.PR_NUMBER }}"
