name: "merge pull"

on:
  push:
    branches:
      - develop

jobs:
  get-pr-number:
    if: contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Numbers
        id: get_pr_number
        run: |
          echo "message ${{ github.event.head_commit.message }}"
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=Merge pull request #)\d+')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Print PR Number
        run: echo "The PR number is ${{ env.PR_NUMBER }}"

  create-metadata-artifact: 
    runs-on: ubuntu-latest
    steps:
      - name: Create release metadata artifact
        run: |
          commit_message=$(echo "${{ github.event.head_commit.message }}" | jq -R . | sed ':a;N;$!ba;s/\n/\\n/g')
          jq -n \
            --arg compare "${{ github.event.compare }}" \
            --arg commitMessage """$commit_message""" \
           '{compare: $compare, "commit-message": $commitMessage}' > release-metadata.json
      - name: Upload release metadata
        uses: actions/upload-artifact@v4
        with:
          name: release-metadata
          path: release-metadata.json
