on:
  push:
    branches:
      - main

jobs:
  get-pr-number:
    if: contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Number
        id: get_pr_number
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | \
            jq -r '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Print PR Number
        run: echo "The PR number is ${{ env.PR_NUMBER }}"
