name: Pull Requests hello

on:
  pull_request

jobs:
  ci:
    if: (!(contains(github.head_ref, 'xxxx') || contains(github.head_ref, 'xxxxx')))
    runs-on: ubuntu-latest
    steps:
      - name: output github ref
        run: echo "branch name ${{ github.head_ref }} and ${{ github.ref_name }}"
