name: Release Workflow
run-name: ${{ github.actor }} running ${{ github.ref_name }} workflow
concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - release**
  workflow_dispatch:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: version
        id: version
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: patch
          source: tags
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.nextVersion }}
          tag_name: ${{ steps.version.outputs.nextVersion }}
#      - name: release stuff
#        id: release
#        run: |
#          git fetch origin refs/notes/commits:refs/notes/commits
#          notes_output="$(git notes show 6b10fcaf671a2ddde3842b7c81391139bf901d3a)"
#          echo "id=$notes_output" >> $GITHUB_OUTPUT
#      - name: git notes output
#        run: |
#          echo "output from step ${{ steps.release.outputs.id }}"
#      - name: release id from notes
#        run: |
#          releaseId="${{ steps.release.outputs.id }}"
#          id=${releaseId#*:}
#          echo "we have the release id $id"


#      - name: checkout project
#        uses: actions/checkout@v3
#      - name: Create release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: 'FY24-06-01'
#          release_name: Release FY24-06-01
#          draft: true
#          prerelease: true
#      - name: output release id
#        run: echo "releases id is ${{ steps.create_release.outputs.id }}"
#      - name: add git note
#        run: |
#          git config user.email "fgfgfgfgfg@users.noreply.github.com"
#          git config user.name "fgfgfgfgf"
#          git fetch origin refs/notes/commits:refs/notes/commits
#          git notes add -m "releaseId:${{ steps.create_release.outputs.id }}" -f
#          git notes show
#          git push origin refs/notes/commits:refs/notes/commits
