name: Release Workflows
run-name: ${{ github.actor }} running ${{ github.ref_name }} workflow
concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract branch name
        id: extractRelease
        run: |
          branch_ref=${{ github.ref }}
          branch_name=${branch_ref##*/}
          echo "name=$branch_name" >> $GITHUB_OUTPUT
          echo "Branch Name: $branch_name"
      - name: Add release id to git note
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git fetch origin refs/notes/commits:refs/notes/commits
          git notes add -m "releaseId:${{ steps.create_release.outputs.id }}" -f
          git notes show
          git push origin refs/notes/commits:refs/notes/commits
