name: Release Workflow
run-name: ${{ github.actor }} running ${{ github.ref_name }} workflow
concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - release**
  workflow_dispatch:

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: release
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin refs/notes/commits:refs/notes/commits
          notes_output="$(git notes show fe5cef8526ed6857a011aa8295ecd0843e673e40)"
          echo "blar=boom" >> $GITHUB_OUTPUT
          echo "from the notes $notes_output"
          echo "output from within the same step ${{ steps.release.outputs.blar }}"
      - name: git notes output
        run: |
          echo "output from step ${{ needs.tag_release.release.outputs.blar }}"
#          git notes add -m "Testing notes with githubfgdfgdgd" -f
#          git push origin "refs/notes/*"
#      - name: checkout project
#        uses: actions/checkout@v3
#      - name: Create release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: 'FY24-06-01'
#          release_name: Release FY24-06-01
#          draft: true
#          prerelease: true
#      - name: output release id
#        run: echo "releases id is ${{ steps.create_release.outputs.id }}"
#      - name: add git note
#        run: |
#          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#          git config user.name "${GITHUB_ACTOR}"
#          git fetch origin "refs/notes/*:refs/notes/*"
#          git notes add -m 'releaseId:oh hello' -f
#          git notes show
#          git push origin "refs/notes/*"
