name: "Release sha"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: commit-sha
          path: commit-sha.txt


      - name: Read commit SHA
        id: read_sha
        run: echo "SHA=$(cat commit-sha)" >> $GITHUB_ENV

      - name: Use commit SHA
        run: echo "The commit SHA from the first workflow is ${{ env.SHA }}"