name: Rollback
on:
  workflow_dispatch:
    inputs:
      description:
        type: string
        required: true
        description: Reason for SNOW
      sha:
        type: string
        required: false
        description: just for testing purposes

jobs:
  setup:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on:
      - self-hosted
      - build
    outputs:
      release-shortSha: ${{ steps.release-meta.outputs.shortSha }}
      release-name: ${{ steps.release-meta.outputs.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Get release meta
        id: release-meta
        run: |
          echo "shortSha=$(echo ${{ github.sha }} | cut -c 1-8)" >> $GITHUB_OUTPUT
          echo "name=$(echo ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "### Rollback to release :hash:" >> $GITHUB_STEP_SUMMARY
          echo "\`$(echo ${{ github.ref_name }}`" >> $GITHUB_STEP_SUMMARY
      - name: Find current latest release
        id: latest
        run: |
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm rollback
        run: |
          echo "🔄 Current latest release: ${{ steps.latest.outputs.latest_tag }}"
          echo "🔙 Rolling back to: ${{ github.ref_name}}"

#  service-now:
#    uses: sainsburys-tech/navigation-actions/.github/workflows/service-now-create.yaml@v7.5
#    with:
#      app: ui-pdp
#      bosun-config: ./config/devops/bosun/bosun.yaml
#      job-name: service-now / Create ServiceNow Change request
#      assignment-group: "Navigation & PDP"
#      deployment-item: "GM eComm - UI PDP"
#      description: "Rollback: Due to ${{ inputs.description }}"
#
#  deploy:
#    needs: [ setup, service-now ]
#    strategy:
#      matrix:
#        brand: [ ARGOS, HABITAT, TU ]
#    uses: sainsburys-tech/navigation-actions/.github/workflows/deploy-app.yaml@v7.5
#    with:
#      app: ui-pdp
#      tags: $ECR/$BOSUN_PRODUCT/$BOSUN_APP:${{ matrix.brand }}-prd-$SHORT_SHA
#      job-name: deploy (${{ matrix.brand }}) / deploy
#      bosun-config: ./config/devops/bosun/bosun.yaml
#      deploy-suffix: ${{ matrix.brand }}
#      brand: ${{ matrix.brand }}
#      environment: prd
#      changeId: ${{ needs.service-now.outputs.changeId }}
#      notifications: true
#
#  newrelic-deployment-marker:
#    needs: [ deploy, setup ]
#    runs-on: ubuntu-latest
#    name: New Relic
#    strategy:
#      matrix:
#        brand: [argos, habitat, tu]
#    steps:
#      - name: New Relic Application Deployment Marker
#        uses: newrelic/deployment-marker-action@v2.5.0
#        with:
#          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
#          guid: ${{ vars[format('NEW_RELIC_DEPLOYMENT_ENTITY_GUID_{0}_PDP_UI_PRD', matrix.brand)] }}
#          version: Rollback-${{ fromJson(needs.setup.outputs.release-meta).release-name }}
#          description: "Rollback: Due to ${{ inputs.description }}"
#          user: ${{ github.actor }}
#          deeplink: "https://github.com/sainsburys-tech/argos-pdp-ui-service/actions/runs/${{ github.run_id }}"
