name: "merge pull listener"

on:
  workflow_run:
    workflows: ["merge pull"]
    types:
      - completed

jobs:
  check-status:
    if: github.event.workflow_run.head_branch == 'main'
    runs-on: [ self-hosted, build ]
    outputs:
      conclusion: ${{ steps.get-conclusion.outputs.conclusion }}

    steps:
      - name: Get triggering workflow conclusion
        id: get-conclusion
        run: |
          conclusion=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} \
            --jq '.conclusion')
          echo "Conclusion: $conclusion"
          echo "conclusion=$conclusion" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  setup:
    needs: [check-status]
    if: needs.check-status.outputs.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      compare: ${{ steps.release-meta.outputs.compare }}
      commit-message: ${{ steps.release-meta.outputs.commit-message }}
      release-name: ${{ steps.release-meta.outputs.release-name }}
      short-sha: ${{ steps.release-meta.outputs.short-sha }}

    steps:
      - name: Get artifact download URL
        id: get-artifact-url
        run: |
          run_id="${{ github.event.workflow_run.id }}"
          artifacts_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/artifacts"
          echo "Fetching artifacts from $artifacts_url"

          curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$artifacts_url" > artifacts.json

          # Find the download URL of the artifact named "release-metadata"
          download_url=$(jq -r '.artifacts[] | select(.name == "release-metadata") | .archive_download_url' artifacts.json)

          if [ -z "$download_url" ]; then
            echo "❌ Artifact 'release-metadata' not found."
            exit 1
          fi

          echo "download_url=$download_url" >> $GITHUB_OUTPUT

      - name: Download and unzip artifact
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${{ steps.get-artifact-url.outputs.download_url }}" -o artifact.zip
          unzip artifact.zip -d metadata

      - name: Set release metadata
        id: release-meta
        run: |
          echo "release-name=${{ vars.PROJECT_ID }}-$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
          short_sha=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-8)
          echo "short-sha=$short_sha" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE" >> "$GITHUB_OUTPUT"
          COMPARE=$(jq -r '.["compare"]' ./metadata/release-metadata.json)
          echo "compare=$COMPARE" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE" >> "$GITHUB_OUTPUT"
          COMMIT_MESSAGE=$(jq -r '.["commit-message"]' ./metadata/release-metadata.json)
          echo "commit-message<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMIT_MESSAGE" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  test-output:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Output release-meta
        run: |
          echo "commit-message : ${{ needs.setup.outputs.commit-message }}"
          echo "release name : ${{ needs.setup.outputs.release-name }}"
          echo "compare : ${{ needs.setup.outputs.compare }}"
          echo "short-sha : ${{ needs.setup.outputs.short-sha }}"

      