name: "merge pull listener"

on:
  workflow_run:
    workflows: ["merge pull"]
    types:
      - completed

jobs:
  setup:
    outputs:
      release-meta: ${{ steps.release-meta.outputs.data }}
      release-name: ${{ steps.release-meta.outputs.release-name }}
    if: github.event.workflow_run.head_branch == 'main'
    runs-on: [ self-hosted, build ]

    steps:
      - name: Download release metadata
        uses: actions/download-artifact@v4
        with:
          name: release-metadata
          path: ./metadata
      - name: Set release metadata
        id: release-meta
        run: |
          metadata=$(jq -c . ./metadata/release-metadata.json)
          echo "data=$metadata" >> $GITHUB_OUTPUT
          echo "release-name=${{ vars.PROJECT_ID }}-$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

  test-output:
    needs: [setup]
    runs-on: [ self-hosted, build ]
    steps:
      - name: Output release-meta
        run: |
          echo "compare : ${{ fromJson(needs.setup.outputs.release-meta).compare }}"
          echo "compare : ${{ fromJson(needs.setup.outputs.release-meta).commit-message }}"
          echo $GITHUB_SHA
          echo $SHORT_SHA
       